"""empty message

Revision ID: 3cc4c7ca4949
Revises: 58058ee9195a
Create Date: 2023-01-25 23:45:30.247118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc4c7ca4949'
down_revision = '58058ee9195a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_column('planet')
        batch_op.drop_column('character')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
